### ISSUE TITLE
Improvements & Edits

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-oil-gas-ternary#2]
This issue is open for suggestions/improvements.

Current app looks like:

![Screencast](https://user-images.githubusercontent.com/35306149/57161894-afa9db80-6dba-11e9-8265-039c26cf1220.gif)

1. Currently, selecting from legend is done by bar-click, which could be done by plotly.js legendclick. One workaround is to add a callback for legendclick triggered callback (restyledData supported in dcc >0.45.0) on production plot plotting& sorting, allows it responds both to data select, and legend click. In this way bar plot could be removed to avoid confusing(and replaced with other plots).
[x] Solved
2. group legend for production plot if possible, individual production plot 
3. ~~for production plot, log y axis for a cleaner display~~
4. Symbolic representation for different operators. So far we have a controller to select operators, but no other information on this app reflects operator groups(This has to be addressed). In spotfire tern mock this was done by symbol shape, which is currently not supported in our scattermapbox marker trace, could take a look at maki-icon to see whether it's possible to import customized icon.
- [x] Unfortunately maki doesn't support symbol color. Add to hover text and group production if needed

<img width="884" alt="Screen Shot 2019-05-03 at 3 43 56 PM" src="https://user-images.githubusercontent.com/35306149/57161745-4f1a9e80-6dba-11e9-9ef5-4594b8526e19.png">

@jackparmer I'll keep this updated and more suggestions/clarifications are welcome.

**Comment by jackparmer** [comment]
> In this way bar plot could be removed to avoid confusing(and replaced with other plots).

I actually really like the bar plot! But things start to get confusing to me if I click on the bars and legend at the same time. The inverse option is to make the plotly.js legends on the ternary chart and mapbox map non-interactive, so filtering can only be done by the bar chart

**Comment by ycaokris** [comment]
> > In this way bar plot could be removed to avoid confusing(and replaced with other plots).
> 
> I actually really like the bar plot! But things start to get confusing to me if I click on the bars and legend at the same time. The inverse option is to make the plotly.js legends on the ternary chart and mapbox map non-interactive, so filtering can only be done by the bar chart

'disable legend click' 👍
